### ISSUE TITLE
getting UnicodeDecodeError

### ISSUE THREAD

**Issue by cyber778** [koterpillar/aloe_django#23] opened 2015-10-08 12:15 UTC
i have my setting set like this in production:

``` python
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'djcelery',
    'djsupervisor',
    'djrill',
    'guardian',
    'storages',
    'timezone_field',
    'aloe_django',
)
```

unless I comment out  'aloe_django' I get this message:

``` bash
Traceback (most recent call last):
  File "/var/webapp/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/alexarsh/.virtualenvs/webapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/alexarsh/.virtualenvs/webapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/alexarsh/.virtualenvs/webapp/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/alexarsh/.virtualenvs/webapp/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/alexarsh/.virtualenvs/webapp/local/lib/python2.7/site-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/alexarsh/.virtualenvs/webapp/local/lib/python2.7/site-packages/aloe_django/__init__.py", line 13, in <module>
    from aloe.testclass import TestCase as AloeTestCase
  File "/home/alexarsh/.virtualenvs/webapp/local/lib/python2.7/site-packages/aloe/testclass.py", line 26, in <module>
    from aloe.parser import (
  File "/home/alexarsh/.virtualenvs/webapp/local/lib/python2.7/site-packages/aloe/parser.py", line 21, in <module>
    from gherkin3.dialect import Dialect
  File "/home/alexarsh/.virtualenvs/webapp/local/lib/python2.7/site-packages/gherkin3/dialect.py", line 12, in <module>
    DIALECTS = json.load(file, encoding='utf-8')
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    return loads(fp.read(),
  File "/home/alexarsh/.virtualenvs/webapp/lib/python2.7/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 266: ordinal not in range(128)
```

**Comment by koterpillar** [comment] 2015-10-09 02:27
What's the output of `locale`?

**Comment by koterpillar** [comment] 2015-10-09 10:11
I've reproduced this with `LC_ALL=en_US.latin1`. Seems to be a bug in gherkin3, will take a look. Meanwhile, set the locale to use UTF-8 as a workaround.

**Comment by koterpillar** [comment] 2015-10-09 10:17
Turns out it's already fixed in https://github.com/cucumber/gherkin3/commit/7833ee9b70446ce92b88331bea31b6389d3752ab. Install `gherkin3>=3.1.2` to fix.

**Comment by koterpillar** [comment] 2015-10-09 10:37
Fixed in aloe 0.0.29.

**Closed as completed** 2015-10-09 10:37 UTC

**Comment by cyber778** [comment] 2015-10-11 08:07
I had 3.1.1, after our release I'll see if It works again, Thanks!

**Comment by koterpillar** [comment] 2015-10-11 08:11
Note: you will have to update Aloe as well, otherwise it won't work with newer Gherkin3.
